T(P(p(32,35),p(46,32),p(48,33),p(54,34),p(56,35),p(78,34)),V(v(0,0),v(416,-14),v(464,0),v(768,-12),v(960,-7),v(1136,-11),v(1280,-9),v(2408,-11)))
T(P(p(46,32),p(54,34),p(56,35),p(72,35)),V(v(0,0),v(160,-10),v(416,-14),v(464,0),v(488,-7),v(768,-12),v(960,-7),v(1136,-11),v(1280,-9),v(1992,-9),v(2032,-11),v(2062,-15),v(2280,-14),v(2384,1)))
T(P(p(48,33),p(54,34),p(56,35),p(78,34)),V(v(0,0),v(160,-10),v(416,-14),v(464,0),v(624,-5),v(768,-12),v(960,-7),v(1008,-5),v(1136,-11),v(1234,-5),v(1280,-9),v(1320,-7),v(2060,-16),v(2160,-14),v(2384,-11),v(2408,-11)))
T(P(p(32,35),p(40,31),p(46,32),p(54,34)),V(v(0,0),v(416,-14),v(464,0),v(768,-12),v(960,-7),v(1136,-11),v(1280,-9),v(2096,-9),v(2328,-9),v(2432,-11)))
T(P(p(118,20),p(120,19),p(120,24),p(126,18),p(128,17),p(128,26)),V(v(0,0),v(64,2),v(1248,2),v(1876,-3),v(1880,-5),v(2160,3),v(2312,10)))
T(P(p(46,32),p(48,33),p(54,34),p(64,36)),V(v(0,0),v(128,-12),v(160,-10),v(416,-14),v(464,0),v(960,-7),v(1048,-13),v(1080,-6),v(1088,-4),v(1136,-11),v(1280,-9),v(1720,-6),v(1910,-15),v(1918,-8),v(2208,-14),v(2432,-11)))

numberOfNotes 1665
tatumsPerBar null
barOneStartsAt null
compressionRatio 1.1594707520891365
runningTime 10831
encodingLength 1436
encodingLengthWithoutResidualPointSet 222
numberOfResidualPoints 1214
percentageOfResidualPoints 72.91291291291292
compressionRatioWithoutResidualPointSet 2.0315315315315314
title Bach-JS-Contrapunctus-VI.midi
numberOfTECs 18
inputFilePath /Users/susanne/Repos/omnisia/Releases/20251202/./data/Bach-JS-Contrapunctus-VI/Bach-JS-Contrapunctus-VI.midi
outputFilePath /Users/susanne/Repos/omnisia/Releases/20251202/./output/Bach-JS-Contrapunctus-VI-midi/Bach-JS-Contrapunctus-VI-diat.Forth
logFilePath /Users/susanne/Repos/omnisia/Releases/20251202/./output/Bach-JS-Contrapunctus-VI-midi/Bach-JS-Contrapunctus-VI-diat.log
outputFileExtension Forth
isDiatonic true
withoutChannel10 true
encoderName com.chromamorph.points022.ForthEncoding
forMirex false
mode Raw
topNPatterns 6

Parameter values
================
Basic algorithm: (-a): Forth
Input file (-i): /Users/susanne/Repos/omnisia/Releases/20251202/./data/Bach-JS-Contrapunctus-VI/Bach-JS-Contrapunctus-VI.midi
Output directory (-o): /Users/susanne/Repos/omnisia/Releases/20251202/./output/Bach-JS-Contrapunctus-VI-midi
Morphetic (diatonic) pitch (-d): true
MIREX (-m): false
Compactness trawler (-ct): true
Minimum compactness of trawled patterns (-cta): 0.5
Minimum size of trawled patterns (-ctb): 4
For r superdiagonals (-rsd): true
r (-r): 3
Remove redundant translators (-rrt): true
Minimum TEC compactness (-minc): 0.5
Minimum pattern size (-min): 4
Maximum pattern size (-max): 10
Merge TECS (-merge): true
Minimum match size if TECs are merged (-minm): 6
Number of iterations if TECs are merged (-spins): 8
Remove channel 10 (drum channel) in MIDI (-no10): true
Help requested (-h): false
Draw analysis (-draw): true
Minimum compression ratio in Forth's algorithm (-crlow): 0.3
Maximum compression ratio in Forth's algorithm (-crhi): 0.9
Minimum compactness threshold in Forth's algorithm (-comlow): 0.3
Maximum compactness threshold in Forth's algorithm (-comhi): 0.9
c_min threshold in Forth's algorithm (-cmin): 10
sigma_min threshold in Forth's algorithm (-sigmin): 0.4
Using bounding-box compactness in Forth's algorithm (-bbcomp): true
Appending date to output directories (-nodate) (N.B.: if true, then NO DATE APPENDED): true
Using BB mode in MIREX output (-bbmode): false
Using Segment mode in MIREX output (-segmode): false
Output file (-out): null
Top N Patterns (-top): 6
Basic algorithm used by RecurSIA (-recalg): COSIATEC
Sort TECs by decreasing pattern size (-sortpat): false
Use GPU acceleration (-gpu): false
Draw input point set (-drawps): false
Rhythm only (-rhythm): false
TEC quality priority string (-tecqual): awsvmc
Dual TEC quality priority string (-dualtecqual): awsmvc
Return number of MTPs only (-nummtpsonly): false
Compactness type (-comptype): BOUNDING_BOX
Input file directory (-id): null
Occurrence set file (-occsets): null
Query file (-q): null


