//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for beam-value.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="beam-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="begin"/>
 *     <enumeration value="continue"/>
 *     <enumeration value="end"/>
 *     <enumeration value="forward hook"/>
 *     <enumeration value="backward hook"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "beam-value")
@XmlEnum
public enum BeamValue {

    @XmlEnumValue("begin")
    BEGIN("begin"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("end")
    END("end"),
    @XmlEnumValue("forward hook")
    FORWARD_HOOK("forward hook"),
    @XmlEnumValue("backward hook")
    BACKWARD_HOOK("backward hook");
    private final java.lang.String value;

    BeamValue(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static BeamValue fromValue(java.lang.String v) {
        for (BeamValue c: BeamValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
