//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The beat-unit-tied type indicates a beat-unit within a metronome mark that is tied to the preceding beat-unit. This allows two or more tied notes to be associated with a per-minute value in a metronome mark, whereas the metronome-tied element is restricted to metric relationship marks.
 * 
 * <p>Java class for beat-unit-tied complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="beat-unit-tied">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <group ref="{}beat-unit"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "beat-unit-tied", propOrder = {
    "beatUnit",
    "beatUnitDot"
})
public class BeatUnitTied {

    @XmlElement(name = "beat-unit", required = true)
    protected java.lang.String beatUnit;
    @XmlElement(name = "beat-unit-dot")
    protected List<Empty> beatUnitDot;

    /**
     * Gets the value of the beatUnit property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getBeatUnit() {
        return beatUnit;
    }

    /**
     * Sets the value of the beatUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setBeatUnit(java.lang.String value) {
        this.beatUnit = value;
    }

    /**
     * Gets the value of the beatUnitDot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the beatUnitDot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeatUnitDot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Empty }
     * 
     * 
     * @return
     *     The value of the beatUnitDot property.
     */
    public List<Empty> getBeatUnitDot() {
        if (beatUnitDot == null) {
            beatUnitDot = new ArrayList<>();
        }
        return this.beatUnitDot;
    }

}
