//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The for-part type is used in a concert score to indicate the transposition for a transposed part created from that score. It is only used in score files that contain a concert-score element in the defaults. This allows concert scores with transposed parts to be represented in a single uncompressed MusicXML file.
 * 
 * The optional number attribute refers to staff numbers, from top to bottom on the system. If absent, the child elements apply to all staves in the created part.
 * 
 * <p>Java class for for-part complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="for-part">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="part-clef" type="{}part-clef" minOccurs="0"/>
 *         <element name="part-transpose" type="{}part-transpose"/>
 *       </sequence>
 *       <attGroup ref="{}optional-unique-id"/>
 *       <attribute name="number" type="{}staff-number" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "for-part", propOrder = {
    "partClef",
    "partTranspose"
})
public class ForPart {

    @XmlElement(name = "part-clef")
    protected PartClef partClef;
    @XmlElement(name = "part-transpose", required = true)
    protected PartTranspose partTranspose;
    @XmlAttribute(name = "number")
    protected BigInteger number;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the partClef property.
     * 
     * @return
     *     possible object is
     *     {@link PartClef }
     *     
     */
    public PartClef getPartClef() {
        return partClef;
    }

    /**
     * Sets the value of the partClef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartClef }
     *     
     */
    public void setPartClef(PartClef value) {
        this.partClef = value;
    }

    /**
     * Gets the value of the partTranspose property.
     * 
     * @return
     *     possible object is
     *     {@link PartTranspose }
     *     
     */
    public PartTranspose getPartTranspose() {
        return partTranspose;
    }

    /**
     * Sets the value of the partTranspose property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartTranspose }
     *     
     */
    public void setPartTranspose(PartTranspose value) {
        this.partTranspose = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumber(BigInteger value) {
        this.number = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
