//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The grace type indicates the presence of a grace note. The slash attribute for a grace note is yes for slashed grace notes. The steal-time-previous attribute indicates the percentage of time to steal from the previous note for the grace note. The steal-time-following attribute indicates the percentage of time to steal from the following note for the grace note, as for appoggiaturas. The make-time attribute indicates to make time, not steal time; the units are in real-time divisions for the grace note.
 * 
 * <p>Java class for grace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="grace">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="steal-time-previous" type="{}percent" />
 *       <attribute name="steal-time-following" type="{}percent" />
 *       <attribute name="make-time" type="{}divisions" />
 *       <attribute name="slash" type="{}yes-no" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grace")
public class Grace {

    @XmlAttribute(name = "steal-time-previous")
    protected BigDecimal stealTimePrevious;
    @XmlAttribute(name = "steal-time-following")
    protected BigDecimal stealTimeFollowing;
    @XmlAttribute(name = "make-time")
    protected BigDecimal makeTime;
    @XmlAttribute(name = "slash")
    protected YesNo slash;

    /**
     * Gets the value of the stealTimePrevious property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStealTimePrevious() {
        return stealTimePrevious;
    }

    /**
     * Sets the value of the stealTimePrevious property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStealTimePrevious(BigDecimal value) {
        this.stealTimePrevious = value;
    }

    /**
     * Gets the value of the stealTimeFollowing property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStealTimeFollowing() {
        return stealTimeFollowing;
    }

    /**
     * Sets the value of the stealTimeFollowing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStealTimeFollowing(BigDecimal value) {
        this.stealTimeFollowing = value;
    }

    /**
     * Gets the value of the makeTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMakeTime() {
        return makeTime;
    }

    /**
     * Sets the value of the makeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMakeTime(BigDecimal value) {
        this.makeTime = value;
    }

    /**
     * Gets the value of the slash property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getSlash() {
        return slash;
    }

    /**
     * Sets the value of the slash property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setSlash(YesNo value) {
        this.slash = value;
    }

}
