//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for harmon-closed-value.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="harmon-closed-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="yes"/>
 *     <enumeration value="no"/>
 *     <enumeration value="half"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "harmon-closed-value")
@XmlEnum
public enum HarmonClosedValue {

    @XmlEnumValue("yes")
    YES("yes"),
    @XmlEnumValue("no")
    NO("no"),
    @XmlEnumValue("half")
    HALF("half");
    private final java.lang.String value;

    HarmonClosedValue(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static HarmonClosedValue fromValue(java.lang.String v) {
        for (HarmonClosedValue c: HarmonClosedValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
