//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for line-end.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="line-end">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="up"/>
 *     <enumeration value="down"/>
 *     <enumeration value="both"/>
 *     <enumeration value="arrow"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "line-end")
@XmlEnum
public enum LineEnd {

    @XmlEnumValue("up")
    UP("up"),
    @XmlEnumValue("down")
    DOWN("down"),
    @XmlEnumValue("both")
    BOTH("both"),
    @XmlEnumValue("arrow")
    ARROW("arrow"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    LineEnd(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static LineEnd fromValue(java.lang.String v) {
        for (LineEnd c: LineEnd.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
