//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The listen and listening types, new in Version 4.0, specify different ways that a score following or machine listening application can interact with a performer. The listen type handles interactions that are specific to a note. If multiple child elements of the same type are present, they should have distinct player and/or time-only attributes.
 * 
 * <p>Java class for listen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="listen">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="assess" type="{}assess"/>
 *         <element name="wait" type="{}wait"/>
 *         <element name="other-listen" type="{}other-listening"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listen", propOrder = {
    "assessOrWaitOrOtherListen"
})
public class Listen {

    @XmlElements({
        @XmlElement(name = "assess", type = Assess.class),
        @XmlElement(name = "wait", type = Wait.class),
        @XmlElement(name = "other-listen", type = OtherListening.class)
    })
    protected List<Object> assessOrWaitOrOtherListen;

    /**
     * Gets the value of the assessOrWaitOrOtherListen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the assessOrWaitOrOtherListen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessOrWaitOrOtherListen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Assess }
     * {@link OtherListening }
     * {@link Wait }
     * 
     * 
     * @return
     *     The value of the assessOrWaitOrOtherListen property.
     */
    public List<Object> getAssessOrWaitOrOtherListen() {
        if (assessOrWaitOrOtherListen == null) {
            assessOrWaitOrOtherListen = new ArrayList<>();
        }
        return this.assessOrWaitOrOtherListen;
    }

}
