//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notehead-value.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="notehead-value">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="slash"/>
 *     <enumeration value="triangle"/>
 *     <enumeration value="diamond"/>
 *     <enumeration value="square"/>
 *     <enumeration value="cross"/>
 *     <enumeration value="x"/>
 *     <enumeration value="circle-x"/>
 *     <enumeration value="inverted triangle"/>
 *     <enumeration value="arrow down"/>
 *     <enumeration value="arrow up"/>
 *     <enumeration value="circled"/>
 *     <enumeration value="slashed"/>
 *     <enumeration value="back slashed"/>
 *     <enumeration value="normal"/>
 *     <enumeration value="cluster"/>
 *     <enumeration value="circle dot"/>
 *     <enumeration value="left triangle"/>
 *     <enumeration value="rectangle"/>
 *     <enumeration value="none"/>
 *     <enumeration value="do"/>
 *     <enumeration value="re"/>
 *     <enumeration value="mi"/>
 *     <enumeration value="fa"/>
 *     <enumeration value="fa up"/>
 *     <enumeration value="so"/>
 *     <enumeration value="la"/>
 *     <enumeration value="ti"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "notehead-value")
@XmlEnum
public enum NoteheadValue {

    @XmlEnumValue("slash")
    SLASH("slash"),
    @XmlEnumValue("triangle")
    TRIANGLE("triangle"),
    @XmlEnumValue("diamond")
    DIAMOND("diamond"),
    @XmlEnumValue("square")
    SQUARE("square"),
    @XmlEnumValue("cross")
    CROSS("cross"),
    @XmlEnumValue("x")
    X("x"),
    @XmlEnumValue("circle-x")
    CIRCLE_X("circle-x"),
    @XmlEnumValue("inverted triangle")
    INVERTED_TRIANGLE("inverted triangle"),
    @XmlEnumValue("arrow down")
    ARROW_DOWN("arrow down"),
    @XmlEnumValue("arrow up")
    ARROW_UP("arrow up"),
    @XmlEnumValue("circled")
    CIRCLED("circled"),
    @XmlEnumValue("slashed")
    SLASHED("slashed"),
    @XmlEnumValue("back slashed")
    BACK_SLASHED("back slashed"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("cluster")
    CLUSTER("cluster"),
    @XmlEnumValue("circle dot")
    CIRCLE_DOT("circle dot"),
    @XmlEnumValue("left triangle")
    LEFT_TRIANGLE("left triangle"),
    @XmlEnumValue("rectangle")
    RECTANGLE("rectangle"),
    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("do")
    DO("do"),
    @XmlEnumValue("re")
    RE("re"),
    @XmlEnumValue("mi")
    MI("mi"),
    @XmlEnumValue("fa")
    FA("fa"),
    @XmlEnumValue("fa up")
    FA_UP("fa up"),
    @XmlEnumValue("so")
    SO("so"),
    @XmlEnumValue("la")
    LA("la"),
    @XmlEnumValue("ti")
    TI("ti"),
    @XmlEnumValue("other")
    OTHER("other");
    private final java.lang.String value;

    NoteheadValue(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static NoteheadValue fromValue(java.lang.String v) {
        for (NoteheadValue c: NoteheadValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
