//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for numeral-mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="numeral-mode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="major"/>
 *     <enumeration value="minor"/>
 *     <enumeration value="natural minor"/>
 *     <enumeration value="melodic minor"/>
 *     <enumeration value="harmonic minor"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "numeral-mode")
@XmlEnum
public enum NumeralMode {

    @XmlEnumValue("major")
    MAJOR("major"),
    @XmlEnumValue("minor")
    MINOR("minor"),
    @XmlEnumValue("natural minor")
    NATURAL_MINOR("natural minor"),
    @XmlEnumValue("melodic minor")
    MELODIC_MINOR("melodic minor"),
    @XmlEnumValue("harmonic minor")
    HARMONIC_MINOR("harmonic minor");
    private final java.lang.String value;

    NumeralMode(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static NumeralMode fromValue(java.lang.String v) {
        for (NumeralMode c: NumeralMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
