//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Ornaments can be any of several types, followed optionally by accidentals. The accidental-mark element's content is represented the same as an accidental element, but with a different name to reflect the different musical meaning.
 * 
 * <p>Java class for ornaments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ornaments">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence maxOccurs="unbounded" minOccurs="0">
 *         <choice>
 *           <element name="trill-mark" type="{}empty-trill-sound"/>
 *           <element name="turn" type="{}horizontal-turn"/>
 *           <element name="delayed-turn" type="{}horizontal-turn"/>
 *           <element name="inverted-turn" type="{}horizontal-turn"/>
 *           <element name="delayed-inverted-turn" type="{}horizontal-turn"/>
 *           <element name="vertical-turn" type="{}empty-trill-sound"/>
 *           <element name="inverted-vertical-turn" type="{}empty-trill-sound"/>
 *           <element name="shake" type="{}empty-trill-sound"/>
 *           <element name="wavy-line" type="{}wavy-line"/>
 *           <element name="mordent" type="{}mordent"/>
 *           <element name="inverted-mordent" type="{}mordent"/>
 *           <element name="schleifer" type="{}empty-placement"/>
 *           <element name="tremolo" type="{}tremolo"/>
 *           <element name="haydn" type="{}empty-trill-sound"/>
 *           <element name="other-ornament" type="{}other-placement-text"/>
 *         </choice>
 *         <element name="accidental-mark" type="{}accidental-mark" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attGroup ref="{}optional-unique-id"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ornaments", propOrder = {
    "trillMarkOrTurnOrDelayedTurn"
})
public class Ornaments {

    @XmlElementRefs({
        @XmlElementRef(name = "trill-mark", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "delayed-turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inverted-turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "delayed-inverted-turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "vertical-turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inverted-vertical-turn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "shake", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wavy-line", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mordent", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inverted-mordent", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "schleifer", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tremolo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "haydn", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "other-ornament", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "accidental-mark", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> trillMarkOrTurnOrDelayedTurn;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the trillMarkOrTurnOrDelayedTurn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the trillMarkOrTurnOrDelayedTurn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrillMarkOrTurnOrDelayedTurn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AccidentalMark }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyPlacement }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyTrillSound }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyTrillSound }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyTrillSound }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyTrillSound }{@code >}
     * {@link JAXBElement }{@code <}{@link EmptyTrillSound }{@code >}
     * {@link JAXBElement }{@code <}{@link HorizontalTurn }{@code >}
     * {@link JAXBElement }{@code <}{@link HorizontalTurn }{@code >}
     * {@link JAXBElement }{@code <}{@link HorizontalTurn }{@code >}
     * {@link JAXBElement }{@code <}{@link HorizontalTurn }{@code >}
     * {@link JAXBElement }{@code <}{@link Mordent }{@code >}
     * {@link JAXBElement }{@code <}{@link Mordent }{@code >}
     * {@link JAXBElement }{@code <}{@link OtherPlacementText }{@code >}
     * {@link JAXBElement }{@code <}{@link Tremolo }{@code >}
     * {@link JAXBElement }{@code <}{@link WavyLine }{@code >}
     * 
     * 
     * @return
     *     The value of the trillMarkOrTurnOrDelayedTurn property.
     */
    public List<JAXBElement<?>> getTrillMarkOrTurnOrDelayedTurn() {
        if (trillMarkOrTurnOrDelayedTurn == null) {
            trillMarkOrTurnOrDelayedTurn = new ArrayList<>();
        }
        return this.trillMarkOrTurnOrDelayedTurn;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
