//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for over-under.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="over-under">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="over"/>
 *     <enumeration value="under"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "over-under")
@XmlEnum
public enum OverUnder {

    @XmlEnumValue("over")
    OVER("over"),
    @XmlEnumValue("under")
    UNDER("under");
    private final java.lang.String value;

    OverUnder(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static OverUnder fromValue(java.lang.String v) {
        for (OverUnder c: OverUnder.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
