//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Page layout can be defined both in score-wide defaults and in the print element. Page margins are specified either for both even and odd pages, or via separate odd and even page number values. The type is not needed when used as part of a print element. If omitted when used in the defaults element, "both" is the default.
 * 
 * If no page-layout element is present in the defaults element, default page layout values are chosen by the application.
 * 
 * When used in the print element, the page-layout element affects the appearance of the current page only. All other pages use the default values as determined by the defaults element. If any child elements are missing from the page-layout element in a print element, the values determined by the defaults element are used there as well.
 * 
 * <p>Java class for page-layout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="page-layout">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <sequence minOccurs="0">
 *           <element name="page-height" type="{}tenths"/>
 *           <element name="page-width" type="{}tenths"/>
 *         </sequence>
 *         <element name="page-margins" type="{}page-margins" maxOccurs="2" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "page-layout", propOrder = {
    "pageHeight",
    "pageWidth",
    "pageMargins"
})
public class PageLayout {

    @XmlElement(name = "page-height")
    protected BigDecimal pageHeight;
    @XmlElement(name = "page-width")
    protected BigDecimal pageWidth;
    @XmlElement(name = "page-margins")
    protected List<PageMargins> pageMargins;

    /**
     * Gets the value of the pageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPageHeight() {
        return pageHeight;
    }

    /**
     * Sets the value of the pageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPageHeight(BigDecimal value) {
        this.pageHeight = value;
    }

    /**
     * Gets the value of the pageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPageWidth() {
        return pageWidth;
    }

    /**
     * Sets the value of the pageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPageWidth(BigDecimal value) {
        this.pageWidth = value;
    }

    /**
     * Gets the value of the pageMargins property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the pageMargins property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPageMargins().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageMargins }
     * 
     * 
     * @return
     *     The value of the pageMargins property.
     */
    public List<PageMargins> getPageMargins() {
        if (pageMargins == null) {
            pageMargins = new ArrayList<>();
        }
        return this.pageMargins;
    }

}
