//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pedal-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="pedal-type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="start"/>
 *     <enumeration value="stop"/>
 *     <enumeration value="sostenuto"/>
 *     <enumeration value="change"/>
 *     <enumeration value="continue"/>
 *     <enumeration value="discontinue"/>
 *     <enumeration value="resume"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "pedal-type")
@XmlEnum
public enum PedalType {

    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("stop")
    STOP("stop"),
    @XmlEnumValue("sostenuto")
    SOSTENUTO("sostenuto"),
    @XmlEnumValue("change")
    CHANGE("change"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("discontinue")
    DISCONTINUE("discontinue"),
    @XmlEnumValue("resume")
    RESUME("resume");
    private final java.lang.String value;

    PedalType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PedalType fromValue(java.lang.String v) {
        for (PedalType c: PedalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
