//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * The pedal-tuning type specifies the tuning of a single harp pedal.
 * 
 * <p>Java class for pedal-tuning complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="pedal-tuning">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="pedal-step" type="{}step"/>
 *         <element name="pedal-alter" type="{}semitones"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pedal-tuning", propOrder = {
    "pedalStep",
    "pedalAlter"
})
public class PedalTuning {

    @XmlElement(name = "pedal-step", required = true)
    @XmlSchemaType(name = "string")
    protected Step pedalStep;
    @XmlElement(name = "pedal-alter", required = true)
    protected BigDecimal pedalAlter;

    /**
     * Gets the value of the pedalStep property.
     * 
     * @return
     *     possible object is
     *     {@link Step }
     *     
     */
    public Step getPedalStep() {
        return pedalStep;
    }

    /**
     * Sets the value of the pedalStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Step }
     *     
     */
    public void setPedalStep(Step value) {
        this.pedalStep = value;
    }

    /**
     * Gets the value of the pedalAlter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPedalAlter() {
        return pedalAlter;
    }

    /**
     * Sets the value of the pedalAlter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPedalAlter(BigDecimal value) {
        this.pedalAlter = value;
    }

}
