//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Pitch is represented as a combination of the step of the diatonic scale, the chromatic alteration, and the octave.
 * 
 * <p>Java class for pitch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="pitch">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="step" type="{}step"/>
 *         <element name="alter" type="{}semitones" minOccurs="0"/>
 *         <element name="octave" type="{}octave"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pitch", propOrder = {
    "step",
    "alter",
    "octave"
})
public class Pitch {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Step step;
    protected BigDecimal alter;
    @XmlSchemaType(name = "integer")
    protected int octave;

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link Step }
     *     
     */
    public Step getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Step }
     *     
     */
    public void setStep(Step value) {
        this.step = value;
    }

    /**
     * Gets the value of the alter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlter() {
        return alter;
    }

    /**
     * Sets the value of the alter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlter(BigDecimal value) {
        this.alter = value;
    }

    /**
     * Gets the value of the octave property.
     * 
     */
    public int getOctave() {
        return octave;
    }

    /**
     * Sets the value of the octave property.
     * 
     */
    public void setOctave(int value) {
        this.octave = value;
    }

}
