//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for principal-voice-symbol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="principal-voice-symbol">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Hauptstimme"/>
 *     <enumeration value="Nebenstimme"/>
 *     <enumeration value="plain"/>
 *     <enumeration value="none"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "principal-voice-symbol")
@XmlEnum
public enum PrincipalVoiceSymbol {

    @XmlEnumValue("Hauptstimme")
    HAUPTSTIMME("Hauptstimme"),
    @XmlEnumValue("Nebenstimme")
    NEBENSTIMME("Nebenstimme"),
    @XmlEnumValue("plain")
    PLAIN("plain"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    PrincipalVoiceSymbol(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PrincipalVoiceSymbol fromValue(java.lang.String v) {
        for (PrincipalVoiceSymbol c: PrincipalVoiceSymbol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
