//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for right-left-middle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="right-left-middle">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="right"/>
 *     <enumeration value="left"/>
 *     <enumeration value="middle"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "right-left-middle")
@XmlEnum
public enum RightLeftMiddle {

    @XmlEnumValue("right")
    RIGHT("right"),
    @XmlEnumValue("left")
    LEFT("left"),
    @XmlEnumValue("middle")
    MIDDLE("middle");
    private final java.lang.String value;

    RightLeftMiddle(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static RightLeftMiddle fromValue(java.lang.String v) {
        for (RightLeftMiddle c: RightLeftMiddle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
