//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The score-part type collects part-wide information for each part in a score. Often, each MusicXML part corresponds to a track in a Standard MIDI Format 1 file. In this case, the midi-device element is used to make a MIDI device or port assignment for the given track or specific MIDI instruments. Initial midi-instrument assignments may be made here as well. The score-instrument elements are used when there are multiple instruments per track.
 * 
 * <p>Java class for score-part complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="score-part">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identification" type="{}identification" minOccurs="0"/>
 *         <element name="part-link" type="{}part-link" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="part-name" type="{}part-name"/>
 *         <element name="part-name-display" type="{}name-display" minOccurs="0"/>
 *         <element name="part-abbreviation" type="{}part-name" minOccurs="0"/>
 *         <element name="part-abbreviation-display" type="{}name-display" minOccurs="0"/>
 *         <element name="group" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="score-instrument" type="{}score-instrument" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="player" type="{}player" maxOccurs="unbounded" minOccurs="0"/>
 *         <sequence maxOccurs="unbounded" minOccurs="0">
 *           <element name="midi-device" type="{}midi-device" minOccurs="0"/>
 *           <element name="midi-instrument" type="{}midi-instrument" minOccurs="0"/>
 *         </sequence>
 *       </sequence>
 *       <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "score-part", propOrder = {
    "identification",
    "partLink",
    "partName",
    "partNameDisplay",
    "partAbbreviation",
    "partAbbreviationDisplay",
    "group",
    "scoreInstrument",
    "player",
    "midiDeviceAndMidiInstrument"
})
public class ScorePart {

    protected Identification identification;
    @XmlElement(name = "part-link")
    protected List<PartLink> partLink;
    @XmlElement(name = "part-name", required = true)
    protected PartName partName;
    @XmlElement(name = "part-name-display")
    protected NameDisplay partNameDisplay;
    @XmlElement(name = "part-abbreviation")
    protected PartName partAbbreviation;
    @XmlElement(name = "part-abbreviation-display")
    protected NameDisplay partAbbreviationDisplay;
    protected List<java.lang.String> group;
    @XmlElement(name = "score-instrument")
    protected List<ScoreInstrument> scoreInstrument;
    protected List<Player> player;
    @XmlElements({
        @XmlElement(name = "midi-device", type = MidiDevice.class),
        @XmlElement(name = "midi-instrument", type = MidiInstrument.class)
    })
    protected List<Object> midiDeviceAndMidiInstrument;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link Identification }
     *     
     */
    public Identification getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identification }
     *     
     */
    public void setIdentification(Identification value) {
        this.identification = value;
    }

    /**
     * Gets the value of the partLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the partLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartLink }
     * 
     * 
     * @return
     *     The value of the partLink property.
     */
    public List<PartLink> getPartLink() {
        if (partLink == null) {
            partLink = new ArrayList<>();
        }
        return this.partLink;
    }

    /**
     * Gets the value of the partName property.
     * 
     * @return
     *     possible object is
     *     {@link PartName }
     *     
     */
    public PartName getPartName() {
        return partName;
    }

    /**
     * Sets the value of the partName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartName }
     *     
     */
    public void setPartName(PartName value) {
        this.partName = value;
    }

    /**
     * Gets the value of the partNameDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link NameDisplay }
     *     
     */
    public NameDisplay getPartNameDisplay() {
        return partNameDisplay;
    }

    /**
     * Sets the value of the partNameDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameDisplay }
     *     
     */
    public void setPartNameDisplay(NameDisplay value) {
        this.partNameDisplay = value;
    }

    /**
     * Gets the value of the partAbbreviation property.
     * 
     * @return
     *     possible object is
     *     {@link PartName }
     *     
     */
    public PartName getPartAbbreviation() {
        return partAbbreviation;
    }

    /**
     * Sets the value of the partAbbreviation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartName }
     *     
     */
    public void setPartAbbreviation(PartName value) {
        this.partAbbreviation = value;
    }

    /**
     * Gets the value of the partAbbreviationDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link NameDisplay }
     *     
     */
    public NameDisplay getPartAbbreviationDisplay() {
        return partAbbreviationDisplay;
    }

    /**
     * Sets the value of the partAbbreviationDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameDisplay }
     *     
     */
    public void setPartAbbreviationDisplay(NameDisplay value) {
        this.partAbbreviationDisplay = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     * @return
     *     The value of the group property.
     */
    public List<java.lang.String> getGroup() {
        if (group == null) {
            group = new ArrayList<>();
        }
        return this.group;
    }

    /**
     * Gets the value of the scoreInstrument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the scoreInstrument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScoreInstrument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreInstrument }
     * 
     * 
     * @return
     *     The value of the scoreInstrument property.
     */
    public List<ScoreInstrument> getScoreInstrument() {
        if (scoreInstrument == null) {
            scoreInstrument = new ArrayList<>();
        }
        return this.scoreInstrument;
    }

    /**
     * Gets the value of the player property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the player property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Player }
     * 
     * 
     * @return
     *     The value of the player property.
     */
    public List<Player> getPlayer() {
        if (player == null) {
            player = new ArrayList<>();
        }
        return this.player;
    }

    /**
     * Gets the value of the midiDeviceAndMidiInstrument property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the midiDeviceAndMidiInstrument property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMidiDeviceAndMidiInstrument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MidiDevice }
     * {@link MidiInstrument }
     * 
     * 
     * @return
     *     The value of the midiDeviceAndMidiInstrument property.
     */
    public List<Object> getMidiDeviceAndMidiInstrument() {
        if (midiDeviceAndMidiInstrument == null) {
            midiDeviceAndMidiInstrument = new ArrayList<>();
        }
        return this.midiDeviceAndMidiInstrument;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
