//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for staff-divide-symbol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="staff-divide-symbol">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="down"/>
 *     <enumeration value="up"/>
 *     <enumeration value="up-down"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "staff-divide-symbol")
@XmlEnum
public enum StaffDivideSymbol {

    @XmlEnumValue("down")
    DOWN("down"),
    @XmlEnumValue("up")
    UP("up"),
    @XmlEnumValue("up-down")
    UP_DOWN("up-down");
    private final java.lang.String value;

    StaffDivideSymbol(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static StaffDivideSymbol fromValue(java.lang.String v) {
        for (StaffDivideSymbol c: StaffDivideSymbol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
