//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for start-note.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="start-note">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="upper"/>
 *     <enumeration value="main"/>
 *     <enumeration value="below"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "start-note")
@XmlEnum
public enum StartNote {

    @XmlEnumValue("upper")
    UPPER("upper"),
    @XmlEnumValue("main")
    MAIN("main"),
    @XmlEnumValue("below")
    BELOW("below");
    private final java.lang.String value;

    StartNote(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static StartNote fromValue(java.lang.String v) {
        for (StartNote c: StartNote.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
