//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sync-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="sync-type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="none"/>
 *     <enumeration value="tempo"/>
 *     <enumeration value="mostly-tempo"/>
 *     <enumeration value="mostly-event"/>
 *     <enumeration value="event"/>
 *     <enumeration value="always-event"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "sync-type")
@XmlEnum
public enum SyncType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("tempo")
    TEMPO("tempo"),
    @XmlEnumValue("mostly-tempo")
    MOSTLY_TEMPO("mostly-tempo"),
    @XmlEnumValue("mostly-event")
    MOSTLY_EVENT("mostly-event"),
    @XmlEnumValue("event")
    EVENT("event"),
    @XmlEnumValue("always-event")
    ALWAYS_EVENT("always-event");
    private final java.lang.String value;

    SyncType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SyncType fromValue(java.lang.String v) {
        for (SyncType c: SyncType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
