//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for time-separator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="time-separator">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="none"/>
 *     <enumeration value="horizontal"/>
 *     <enumeration value="diagonal"/>
 *     <enumeration value="vertical"/>
 *     <enumeration value="adjacent"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "time-separator")
@XmlEnum
public enum TimeSeparator {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("horizontal")
    HORIZONTAL("horizontal"),
    @XmlEnumValue("diagonal")
    DIAGONAL("diagonal"),
    @XmlEnumValue("vertical")
    VERTICAL("vertical"),
    @XmlEnumValue("adjacent")
    ADJACENT("adjacent");
    private final java.lang.String value;

    TimeSeparator(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static TimeSeparator fromValue(java.lang.String v) {
        for (TimeSeparator c: TimeSeparator.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
