//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for time-symbol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="time-symbol">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="common"/>
 *     <enumeration value="cut"/>
 *     <enumeration value="single-number"/>
 *     <enumeration value="note"/>
 *     <enumeration value="dotted-note"/>
 *     <enumeration value="normal"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "time-symbol")
@XmlEnum
public enum TimeSymbol {

    @XmlEnumValue("common")
    COMMON("common"),
    @XmlEnumValue("cut")
    CUT("cut"),
    @XmlEnumValue("single-number")
    SINGLE_NUMBER("single-number"),
    @XmlEnumValue("note")
    NOTE("note"),
    @XmlEnumValue("dotted-note")
    DOTTED_NOTE("dotted-note"),
    @XmlEnumValue("normal")
    NORMAL("normal");
    private final java.lang.String value;

    TimeSymbol(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static TimeSymbol fromValue(java.lang.String v) {
        for (TimeSymbol c: TimeSymbol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
