//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.musicxml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trill-step.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="trill-step">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     <enumeration value="whole"/>
 *     <enumeration value="half"/>
 *     <enumeration value="unison"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "trill-step")
@XmlEnum
public enum TrillStep {

    @XmlEnumValue("whole")
    WHOLE("whole"),
    @XmlEnumValue("half")
    HALF("half"),
    @XmlEnumValue("unison")
    UNISON("unison");
    private final java.lang.String value;

    TrillStep(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static TrillStep fromValue(java.lang.String v) {
        for (TrillStep c: TrillStep.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
